# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"
          channel: "stable"

      # Show the Flutter version.
      - name: Show flutter configuration
        run: |
          flutter doctor -v

      # Build and deploy.
      - name: Building web
        run: |
          flutter build web --release --no-tree-shake-icons --pwa-strategy=none -t lib/main.dart

      # Archive the web build.
      - name: Archive the web build
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: build/web/
          retention-days: 1